apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lw5l4z14z-go 
  janus-idp.io/tekton: lw5l4z14z-go
  backstage.io/kubernetes-id: lw5l4z14z-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lw5l4z14z-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml