apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lw5l4z14z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lw5l4z14z-go 
  name: lw5l4z14z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lw5l4z14z-go 
